homepage:
    path:   /
    defaults: {_controller: 'Controller\DefaultController::indexAction'}
chapter_display:
    path:   /chapter/display
    defaults: {_controller: 'Controller\ChapterController::listAction'}
chapter_add:
    path:   /chapter/add
    defaults: {_controller: 'Controller\ChapterController::addAction'}
chapter_update:
    path:   /chapter/update/{id}
    defaults: {_controller: 'Controller\ChapterController::updateAction'}
chapter_delete:
    path:   /chapter/delete/{id}
    defaults: {_controller: 'Controller\ChapterController::deleteAction'}
comment_moderate:
    path:   /comment/moderate
    defaults: {_controller: 'Controller\CommentController::listAction'}
comment_add:
    path:   /comment/add/{chapter}/{parent}
    defaults: {_controller: 'Controller\CommentController::addAction', parent: null}
comment_update:
    path:   /comment/update/{id}
    defaults: {_controller: 'Controller\CommentController::updateAction'}
comment_delete:
    path:   /comment/delete/{id}
    defaults: {_controller: 'Controller\CommentController::deleteAction'}
comment_report:
    path:   /comment/report/{id}
    defaults: {_controller: 'Controller\CommentController::reportAction'}
admin_login:
    path:   /login
    defaults: {_controller: 'Controller\AdminController::loginAction'}
admin_logout:
    path:   /logout
    defaults: {_controller: 'Controller\AdminController::logoutAction'}
